# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  example_1:
  # Installs tensorflow
  # Installs using conda_install
  # Uses Python 3.6

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

#      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(c("reticulate", "testthat"))
        shell: Rscript {0}

      - name: Example 1
        run: Rscript example_1.R

  example_2:
  # Installs tensorflow
  # Installs using py_install
  # Uses Python 3.6

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

#      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(c("reticulate", "testthat"))
        shell: Rscript {0}

      - name: Example 2
        run: Rscript example_2.R

  example_3:
  # Installs scipy
  # Installs using conda_install
  # Uses Python 3.6

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

#      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(c("reticulate", "testthat"))
        shell: Rscript {0}

      - name: Example 3
        run: Rscript example_3.R

  example_4:
  # Installs scipy
  # Installs using conda_install
  # Uses default Python version

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(c("reticulate", "testthat"))
        shell: Rscript {0}

      - name: Example 4
        run: Rscript example_4.R

  example_5:
  # Installs tensorflow
  # Installs using conda_install
  # Uses current version of Python

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(c("reticulate", "testthat"))
        shell: Rscript {0}

      - name: Example 5
        run: Rscript example_5.R

